spring:
  application:
    name: check-kid-api

  # Auth Database Configuration
  datasource:
    auth:
      jdbc-url: jdbc:postgresql://localhost:5433/checkkid_auth
      username: checkkid_auth_user
      password: devpassword1
      driver-class-name: org.postgresql.Driver

    # Application Database Configuration
    app:
      jdbc-url: jdbc:postgresql://localhost:5432/checkkid
      username: checkkid_user
      password: devpassword2
      driver-class-name: org.postgresql.Driver

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: validate  # Use Flyway for migrations
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  # Flyway Configuration - Disabled because we manage Flyway manually for multiple datasources
  flyway:
    enabled: false
  web:
    error:
      include-message: always
      include-binding-errors: always

# Server Configuration
server:
  port: 8080

# Logging
logging:
  level:
    com.ruby.pro203_exam: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.flywaydb: DEBUG

# JWT Configuration
jwt:
  secret: "secret-key-here-because-we-need-that-super-secret-jwt-key-because-we-are-all-about-security"
  expiration: 43200000  # ms

# Google OAuth Configuration
google:
  client-ids:
    - "231817845094-uosrqoegm0dtt60n18iso1u533h2noau.apps.googleusercontent.com"
    - "231817845094-tm3a42ql593rlkch0af5iq9m1j8pd1aq.apps.googleusercontent.com"
    - "231817845094-em6lk0v2d6ndnrfdcsngv8rf5k8poiju.apps.googleusercontent.com"