spring:
  application:
    name: PRO203_exam

# database config --> insert here

google:
  client-ids:
    - "231817845094-uosrqoegm0dtt60n18iso1u533h2noau.apps.googleusercontent.com"
    - "231817845094-tm3a42ql593rlkch0af5iq9m1j8pd1aq.apps.googleusercontent.com"
    - "231817845094-em6lk0v2d6ndnrfdcsngv8rf5k8poiju.apps.googleusercontent.com"   # <---- Not needed if frontend only tests on android/ios.

jwt:
  secret: "secret-key-here-because-we-need-that-super-secret-jwt-key-because-we-are-all-about-security"
  expiration: 43200000

server:
  port: 8080

logging:
  level:
    com.ruby.pro203_exam: DEBUG
    org.springframework.security: DEBUG
